SELECT 
    id as account_id,
    name,
    parentid as parent_id,
    billingcity as billing_city,
    billingstate as billing_state,
    billingpostalcode as billing_postal_code,
    billingcountry as billing_country,
    billingstatecode as billing_state_code,
    billingcountrycode as billing_country_code,
    phone,
    website,
    industry,
    numberofemployees as number_of_employees,
    currencyisocode as currency_code,
    ownerid as owner_id,
    createddate as created_date,
    createdbyid as created_by_id,
    lastactivitydate as last_activity_date,
    dp_salesforce_18_digit_id__c as sf_18_digit_id,
